#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
# Backgrounded and detached on purpose: on Windows, asking "start" for a named
# browser (e.g. "chrome") that isn't resolvable can pop up a chooser dialog
# that blocks the calling process — that must never be able to stall the
# wizard. The URL is always printed above too, so copy-pasting it manually
# (into whichever browser you actually use) always works as a fallback.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  ( if   command -v cmd.exe      >/dev/null 2>&1; then cmd.exe /c start "" "$url"
    elif command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    fi
  ) >/dev/null 2>&1 &
  disown 2>/dev/null || true
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Scrive le variabili nel .env.local dentro dnd-character-creator/ (dove Vite
# le legge in dev), risolto rispetto alla posizione di QUESTO script — così
# funziona indipendentemente da quale sia la directory corrente della shell
# quando lo lanci (es. "bash /percorso/assoluto/setup-campagna-supabase.sh").
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/dnd-character-creator/.env.local"

# Idempotente: puoi rieseguire questo blocco senza errori anche se l'hai già
# lanciato una volta (ogni "create policy" è preceduto da un "drop" di sicurezza,
# e l'iscrizione alla pubblicazione realtime è dentro un controllo IF NOT EXISTS).
SETUP_SQL='create table if not exists campaign_characters (
  campaign_code text not null,
  character_id text not null,
  data jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (campaign_code, character_id)
);

alter table campaign_characters enable row level security;

drop policy if exists "anon can read campaign_characters" on campaign_characters;
create policy "anon can read campaign_characters"
  on campaign_characters for select
  to anon
  using (true);

drop policy if exists "anon can insert campaign_characters" on campaign_characters;
create policy "anon can insert campaign_characters"
  on campaign_characters for insert
  to anon
  with check (true);

drop policy if exists "anon can update campaign_characters" on campaign_characters;
create policy "anon can update campaign_characters"
  on campaign_characters for update
  to anon
  using (true)
  with check (true);

drop policy if exists "anon can delete campaign_characters" on campaign_characters;
create policy "anon can delete campaign_characters"
  on campaign_characters for delete
  to anon
  using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = '"'"'supabase_realtime'"'"' and schemaname = '"'"'public'"'"' and tablename = '"'"'campaign_characters'"'"'
  ) then
    alter publication supabase_realtime add table campaign_characters;
  end if;
end $$;'

banner "Configura la Campagna (Supabase)"

# ── Stage 1: crea il progetto Supabase ─────────────────────────────────────
stage "Crea un progetto Supabase gratuito"
say "Supabase è il servizio esterno che fa comunicare i dispositivi dei tuoi giocatori con il tuo. Il piano gratuito basta abbondantemente per un gruppo di amici."
open_url "https://supabase.com/dashboard/sign-up"
step "Crea un account (con GitHub o email) se non ne hai già uno."
step "Se te lo chiede, crea prima una 'Organization' (nome a piacere, piano Free) — è solo un contenitore, niente di complicato."
step "Dentro l'organization, clicca 'New project'. Dagli un nome a piacere (es. 'dnd-campagna'), scegli una password per il database (salvala da qualche parte, non ti servirà più in questa procedura) e la regione più vicina a te."
step "Aspetta che il progetto finisca di essere creato (di solito 1-2 minuti)."
pause "Premi Invio quando il progetto è pronto e vedi la sua dashboard"

# ── Stage 2: crea la tabella e le regole di accesso ────────────────────────
stage "Crea la tabella condivisa"
warn "Nota sulla sicurezza: questa app non ha account/login per nessuno. Il 'Codice Campagna' che genererai nell'app è l'unica protezione — chiunque lo conosca può leggere e scrivere i dati di quella campagna. Va bene per un gruppo di amici fidati, non per un uso pubblico: non pubblicare mai il codice campagna."
say "Ora creiamo la tabella che conterrà i personaggi condivisi, con questa premessa di sicurezza applicata (regole permissive perché non c'è login)."
step "Nel menu a sinistra del progetto Supabase, apri 'SQL Editor'."
step "Clicca 'New query'."
step "Copia ESATTAMENTE il blocco SQL qui sotto e incollalo nell'editor:"
printf '\n%s\n' "$SETUP_SQL"
printf '\n'
step "Clicca 'Run' (o Ctrl+Invio). Deve dire 'Success. No rows returned' senza errori."
pause "Premi Invio dopo aver eseguito lo script SQL con successo"

# ── Stage 3: recupera le chiavi API ────────────────────────────────────────
stage "Recupera l'indirizzo e la chiave del progetto"
say "Servono due valori pubblici (non sono password) che l'app userà per parlare con Supabase."
step "Nel progetto Supabase, apri Project Settings (icona ingranaggio in basso a sinistra) → API."
step "Copia il valore 'Project URL' (es. https://xxxxx.supabase.co)."
ask VITE_SUPABASE_URL "Incolla il Project URL:"
step "Copia il valore 'anon public' key (NON 'service_role': quella non va mai usata qui)."
ask VITE_SUPABASE_ANON_KEY "Incolla la anon public key:"
write_env VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"
note "Questi due valori sono stati scritti in $ENV_FILE, per lo sviluppo in locale (npm run dev)."

# ── Stage 4: stesse variabili su Vercel, per il sito online ────────────────
stage "Configura le stesse variabili su Vercel"
say "In locale bastano i valori appena salvati. Il sito online (Vercel) legge le variabili dal proprio pannello, non dal tuo .env.local: vanno inserite anche lì."
open_url "https://vercel.com/dashboard"
step "Apri il progetto collegato al repository GitHub FIUMEZEN/Dnd."
step "Vai su Settings → Environment Variables."
step "Aggiungi una variabile: Name = VITE_SUPABASE_URL, Value = $VITE_SUPABASE_URL (tutti gli ambienti: Production, Preview, Development)."
step "Aggiungi una seconda variabile: Name = VITE_SUPABASE_ANON_KEY, Value = $VITE_SUPABASE_ANON_KEY (stessi ambienti)."
step "Salva, poi vai su 'Deployments', apri i tre puntini sull'ultimo deployment e scegli 'Redeploy' (senza usare la cache), così il sito online prende subito le nuove variabili."
pause "Premi Invio quando hai salvato le variabili su Vercel e avviato il redeploy"

# ── Stage 5: verifica ───────────────────────────────────────────────────────
stage "Verifica che funzioni"
say "Ultimo passo: controlliamo che l'app veda davvero Supabase."
step "In locale: dentro dnd-character-creator/ lancia 'npm run dev' e apri l'indirizzo mostrato (se era già in esecuzione, riavvialo per far leggere il nuovo .env.local)."
step "Nell'app vai su Sezione Master → Campagna."
if confirm "Vedi il pulsante 'Genera codice campagna' invece del messaggio 'Campagna non ancora configurata'?"; then
  note "Configurazione riuscita: la Campagna è attiva."
else
  warn "Se vedi ancora 'non configurata', controlla: 1) che $ENV_FILE contenga le due righe VITE_SUPABASE_*, 2) di aver riavviato 'npm run dev' dopo averlo scritto, 3) che lo script SQL sia stato eseguito senza errori nello Stage 2."
  SKIPPED+=("verifica finale non confermata — vedi i suggerimenti sopra")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
